# Generated by Django 5.2.7 on 2025-12-11 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_order_order_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
