# Generated by Django 5.2.7 on 2025-12-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_delete_category_remove_product_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='filter',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Phones', 'Phones'), ('Headphones', 'Headphones'), ('Phonecases', 'Phonecases'), ('Accessories', 'Accessories')], default='Phones', max_length=50),
        ),
    ]
