# Generated by Django 5.2.7 on 2025-12-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_filter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Phones', 'Phones'), ('Headphones', 'Headphones'), ('Chargers', 'Chargers'), ('Accessories', 'Accessories')], default='Phones', max_length=50),
        ),
    ]
