# Generated by Django 6.0.1 on 2026-02-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_price_product_prices_product_pricet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Fahrräder', 'Fahrräder'), ('Kinderfahrräder', 'Kinderfahrräder'), ('Bestandteile', 'Bestandteile'), ('Ausrüstung', 'Ausrüstung')], default='Fahrräder', max_length=50),
        ),
    ]
