# Generated by Django 6.0.1 on 2026-02-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mountainbikes', 'Mountainbikes'), ('TrekkingFahrräder', 'Trekking Fahrräder'), ('Kinderfahrräder', 'Kinderfahrräder'), ('Bestandteile', 'Bestandteile'), ('Ausrüstung', 'Ausrüstung')], default='Fahrräder', max_length=50),
        ),
    ]
