# Generated by Django 6.0.1 on 2026-02-09 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mountainbikes', 'Mountainbikes'), ('TrekkingFahrräder', 'Trekking Fahrräder'), ('Kinderfahrräder', 'Kinderfahrräder'), ('Bestandteile', 'Bestandteile'), ('Ausrüstung', 'Ausrüstung')], max_length=50),
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_type', models.CharField(choices=[('hour', 'Stunde'), ('day', 'Tag'), ('week', 'Woche'), ('buy', 'Kauf')], max_length=10)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
