# Generated by Django 6.0.1 on 2026-02-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_product_category_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mountainbikes', 'Mountainbikes'), ('TrekkingFahrräder', 'Trekking Fahrräder'), ('Kinderfahrräder', 'Kinderfahrräder'), ('Bestandteile', 'Bestandteile'), ('Ausrüstung', 'Ausrüstung'), ('Reparatur', 'Reparatur')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rental',
            name='price_type',
            field=models.CharField(choices=[('hour', 'Stunde'), ('day', 'Tag'), ('week', 'Woche'), ('buy', 'Kauf'), ('repair', 'Reparatur')], max_length=10),
        ),
    ]
