# Generated by Django 6.0.1 on 2026-02-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_product_category_alter_rental_price_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pricek',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prices',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pricet',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pricew',
        ),
        migrations.AddField(
            model_name='product',
            name='ist_service',
            field=models.BooleanField(default=False, verbose_name='Ist Reparatur/Service'),
        ),
        migrations.AddField(
            model_name='product',
            name='leihbar',
            field=models.BooleanField(default=False, verbose_name='Verleihbar'),
        ),
        migrations.AddField(
            model_name='product',
            name='preis_kauf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kaufpreis'),
        ),
        migrations.AddField(
            model_name='product',
            name='preis_service',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Servicepreis'),
        ),
        migrations.AddField(
            model_name='product',
            name='preis_stunde',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preis pro Stunde'),
        ),
        migrations.AddField(
            model_name='product',
            name='preis_tag',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preis pro Tag'),
        ),
        migrations.AddField(
            model_name='product',
            name='preis_woche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preis pro Woche'),
        ),
        migrations.AddField(
            model_name='product',
            name='verkaufbar',
            field=models.BooleanField(default=False, verbose_name='Verkaufbar'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Bild'),
        ),
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
