# Generated by Django 6.0.1 on 2026-02-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_product_pricek_remove_product_prices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='leasing_available',
            field=models.BooleanField(default=False, verbose_name='Verfügbar für Leasing'),
        ),
        migrations.AddField(
            model_name='product',
            name='preis_leasing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Leasing pro Monat'),
        ),
    ]
